### PR TITLE
Update to work with Webpack 5

### PR DESCRIPTION
**Pull request by rhuitl**
Webpack 5 support and related changes to the README.

### CODE REVIEW

**Comment by princed** [comment]
Wow, didn't know someone was still using this :)

Published as `1.1.0`

**Comment by rhuitl** [comment]
I wish we wouldn't ;-) Thanks for merging and releasing so quickly!

**Comment by princed** [comment]
Accept my condolences then 😂

**Comment by rhuitl** [comment]
According to https://npm-stat.com/charts.html?package=angular-gettext-loader&from=2015-01-01&to=2021-11-17 there are many other poor souls out there:
Bildschirmfoto 2021-11-17 um 12 24 26

**Comment by princed** [comment]
Whoa, it's been growling like a lot since 2019 🤯

**Pull request merged**
